layout_spectrum: 0.7885857
typography_spectrum: 0.5404255
color:
  lightness: 0.7957447
  brandStrength: 0.4276596
  saturation: 0.4
  rhythmicContrast: 0.4553191
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: mennä
