name: mennä
favicon: null
layout_spectrum: 0.44512
typography_spectrum: 0.46524
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020001'
    - '#fafeff'
    - '#3d423e'
    - '#b1b7b7'
    - '#616860'
  brandStrength: 0.4375
  lightness: 0.7957447
  saturation: 0.4375
  rhythmicContrast: 0.4553191
purpose: []
